platform=ios

# APPIUM SERVER
appiumHost=127.0.0.1
appiumPort=4723
isAppiumServerNeeded=true

# DEVICE
deviceName=Tea?s iPhone
platformVersion=18.6.2
udid=00008120-00040DD0010B401E

# IOS APP
bundleId=com.scalefocus.photopixles

# AUTOMATION
automationName=XCUITest
showXcodeLog=true