services:
  frontend:
    image: scalefocusad/photopixels-web:automation
    deploy:
      labels:
        automation.environment:
    ports:
      - '5001:80'
    networks:
      - sf-photos-net
    environment:
      SERVER_URL: 'http://localhost:8888'
    restart: always
    depends_on:
      - backend

  backend:
    image: scalefocusad/photopixels-backend-net:automation
    deploy:
      labels:
        automation.environment:

    ports:
      - '8888:8080'
    networks:
      - sf-photos-net
      - sf-photos-db
    environment:
      ConnectionStrings__PhotosMetadata: 'Host=db;Port=5432;Database=photosdb;Username=postgres;Password=test123'
      Admin__Email: 'testadmin@test.com'
      Admin__Password: 'Test12345!'
      EmailConfiguration__Host: 'mailhog'
      EmailConfiguration__Port: '25'
      EmailConfiguration__Username: 'user'
      EmailConfiguration__UseSsl: false
      EmailConfiguration__CheckCertificateRevocation: false
    restart: always
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    deploy:
      labels:
        automation.environment:
    depends_on:
      - db
    networks:
      - sf-photos

  db:
    image: postgres:14.3
    deploy:
      labels:
        automation.environment:

    networks:
      - sf-photos-db
    environment:
      POSTGRES_DB: 'photosdb'
      POSTGRES_PASSWORD: 'test123'
    restart: always

networks:
  sf-photos-db:
  sf-photos-net: