services:
  frontend:
    image: scalefocusad/photopixels-web:automation
    deploy:
      labels:
        automation.environment:
    ports:
      - '5001:80'
    networks:
      - sf-photos-net
    environment:
      SERVER_URL: 'http://localhost:8888'
    restart: always
    depends_on:
      - backend

  backend:
    image: scalefocusad/photopixels-backend-net:automation
    deploy:
      labels:
        automation.environment:

    ports:
      - '8888:8080'
    networks:
      - sf-photos-net
      - sf-photos-db
    environment:
      ConnectionStrings__PhotosMetadata: 'Host=db;Port=5432;Database=photosdb;Username=postgres;Password=test123'
      Admin__Email: 'testadmin@test.com'
      Admin__Password: 'Test12345!'
      EmailConfiguration__Host: ''
      EmailConfiguration__Port: ''
      EmailConfiguration__Username: ''
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.3
    deploy:
      labels:
        automation.environment:

    networks:
      - sf-photos-db
    environment:
      POSTGRES_DB: 'photosdb'
      POSTGRES_PASSWORD: 'test123'
    restart: always

  selenium-hub:
    image: selenium/hub:4.35.0
    deploy:
      labels:
        automation.environment:
    container_name: selenium-hub
    networks:
      - sf-photos-net
    ports: [ "4442-4444:4442-4444" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://selenium-hub:4444/status > /dev/null" ]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: always
    depends_on:
      - frontend

  chrome:
    image: selenium/node-chrome:126.0-20250808
    deploy:
      labels:
        automation.environment:
    container_name: selenium-node-chrome
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    networks:
      - sf-photos-net
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

  android-emulator:
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64-no-metrics:30.1.2
    container_name: android-emulator
    privileged: true
    networks: [ sf-photos-net ]
    ports: [ "5554:5554", "5555:5555" ]
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      ADBKEY: "/root/.android/adbkey"
      EMULATOR_ARGS: "-no-window -gpu swiftshader_indirect -no-boot-anim -accel on -no-snapshot"
    volumes:
      - ${HOME}/.android/adbkey:/root/.android/adbkey:ro
      - ${HOME}/.android/adbkey.pub:/root/.android/adbkey.pub:ro
    depends_on:
      selenium-hub:
        condition: service_healthy
    healthcheck:
      test: "adb shell getprop sys.boot_completed | grep 1 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s # Give the emulator ample time to start up.

  appium:
    image: appium/appium:latest
    container_name: appium
    networks:
      - sf-photos-net
    depends_on:
      android-emulator:
        condition: service_healthy
    ports: [ "4723:4723" ]
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - APPIUM_ARGS=--base-path / --log-level info
      - CONNECT_TO_GRID=false
    command: >
      sh -lc "
      adb connect android-emulator:5555 &&
      adb wait-for-device &&
      appium --allow-cors --base-path / --log-timestamp"
    healthcheck:
      test: [ "CMD-SHELL",  "curl -sf http://localhost:4723/status > /dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 30

  appium-relay:
    image: selenium/node-base:4.35.0
    deploy:
      labels:
        automation.environment:
    networks:
      - sf-photos-net
    depends_on:
      selenium-hub:
        condition: service_started
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_RELAY_URL=http://appium:4723
      - SE_NODE_RELAY_STATUS_ENDPOINT=/status
      - SE_NODE_RELAY_PROTOCOL_VERSION=HTTP/1.1
      - 'SE_NODE_RELAY_STEREOTYPE={"platformName":"Android","appium:automationName":"UiAutomator2","se:name":"Android Emulator"}'
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SESSION_REQUEST_TIMEOUT=300

networks:
  sf-photos-db:
  sf-photos-net: