name: "Build FE"
description: 'Checkout and build the frontend docker image'

env:
  FRONTEND_TAG: scalefocusad/photopixels-web:automation

inputs:
  branch:
    description: 'Branch to checkout'
    required: false
    default: 'main'
  tag:
    description: 'Tag for the docker test image'
    required: false
    default: 'automation'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: "scalefocus/photopixels-web"
        submodules: "recursive"
        ref: ${{ inputs.branch }}

    - name: Build docker image
      run: |
        docker build --no-cache -t $FRONTEND_TAG -f ./Dockerfile .
