name: Photopixels automated tests

on:
  workflow_dispatch:

env:
  AUTOMATION_REPO_PATH: automation
  BACKEND_REPO_PATH: backend
  FRONTEND_REPO_PATH: frontend
  COMPOSE_FILE: automation/utils/docker-compose.yml
  FRONTEND_TAG: scalefocusad/photopixels-web:automation
  BACKEND_TAG: scalefocusad/photopixels-backend-net:automation
  AUTOMATION_TAG: scalefocusad/photopixels-automated-tests:automation

jobs:
  build-fe:
    runs-on: self-hosted
    needs: [ build-be ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: scalefocus/photopixels-web
          submodules: recursive
          fetch-depth: 0
          path: ${{ env.FRONTEND_REPO_PATH }}
      - name: Build docker image
        working-directory: ${{ env.FRONTEND_REPO_PATH }}
        run: |
          docker build --no-cache -t $FRONTEND_TAG -f ./Dockerfile .

  build-be:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          repository: scalefocus/photopixels-backend-net
          submodules: recursive
          fetch-depth: 0
          path: ${{ env.BACKEND_REPO_PATH }}

      - name: Build docker image
        working-directory: ${{ env.BACKEND_REPO_PATH }}
        run: |
          docker build \
           --no-cache \
           --build-arg VERSION="1.0.0" \
           --build-arg VERSION_SUFFIX="" \
           -t $BACKEND_TAG \
           -f ./src/SF.PhotoPixels.API/Dockerfile .

  build-automation:
    runs-on: self-hosted
    needs: [ build-fe ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.AUTOMATION_REPO_PATH }}
      - name: Build docker image
        working-directory: ${{ env.AUTOMATION_REPO_PATH }}
        run: docker build --no-cache -f ./Dockerfile -t "$AUTOMATION_TAG" .

  automation:
    runs-on: self-hosted
    needs: [ build-fe, build-be, build-automation ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.AUTOMATION_REPO_PATH }}
      - name: Show KVM
        run: |
          ls -l /dev/kvm || true
          lsmod | grep kvm || true
      - name: Start environment
        run: |
          chmod +x "${GITHUB_WORKSPACE}/${{ env.AUTOMATION_REPO_PATH }}/utils/create-environment.sh"
          "${GITHUB_WORKSPACE}/${{ env.AUTOMATION_REPO_PATH }}/utils/create-environment.sh" "$COMPOSE_FILE"
      - name: Emulator logs (for debugging if it fails)
        if: failure()
        run: |
          docker logs android-emulator || true

      - name: Run Mobile tests
        id: mobile_tests
        continue-on-error: true
        run: |
          docker run -i --rm \
          -e BASE_URI="http://backend:8080/api" \
          -e WEB_URI="http://frontend:80/" \
          -e APPIUM_HOST="selenium-hub" \
          -e APPIUM_PORT="4444" \
          -e SUITE_NAME="mobile" \
          -e APP_NAME="https://github.com/scalefocus/photopixels-android/releases/download/v.0.4.0/io.photopixels.app-v0.4.0.362345530.-release.apk" \
          -e $APP_PACKAGE="io.photopixels.app" \
          -e ACTIVITY_NAME="io.photopixels.app.MainActivity" \
          --network utils_sf-photos-net \
          $AUTOMATION_TAG

      - name: Cleanup environment
        if: always()
        run: docker compose -f "$COMPOSE_FILE" down --volumes --rmi all --remove-orphans
