name: Self-Hosted Runner Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # build-fe:
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #       with:
  #         repository: "scalefocus/photopixels-"
  #     - name: Build docker image
  #       working-directory: ""
  #       run: |
  #         docker build -t scalefocusad/photopixels-backend-net -f ./src/SF.PhotoPixels.API/Dockerfile .

  build-be:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: "scalefocus/photopixels-backend-net"

      - name: Build docker image
        working-directory: "./photopixels-backend-net"
        run: |
          docker build \
           --no-cache \
           -t scalefocusad/photopixels-backend-net:automation \
           -f ./src/SF.PhotoPixels.API/Dockerfile .
